#change the file path to adjust your computer
setwd('~/Documents/coursera')
powerdata<-read.table('household_power_consumption.txt',header=TRUE,sep=";",stringsAsFactors = FALSE)
mydata<-subset(powerdata, Date %in% c('1/2/2007',"2/2/2007"))
mydata$Date<-as.Date(mydata$Date,"%d/%m/%Y")
newtime<-as.POSIXct(strptime(paste(mydata$Date, mydata$Time,sep = ' '),"%Y-%m-%d %H:%M:%S"))
mydata$weekdays<-weekdays(mydata$Date)
mydata$Global_active_power<-as.numeric(mydata$Global_active_power)
attach(mydata)
png(filename = "plot1.png",width = 480, height = 480)
hist(Global_active_power,xlab='Global active power(kilowatt)',col="red",main='Global_active_power')
dev.off()
