#change the file path to adjust yours
setwd('~/Documents/coursera')
powerdata<-read.table('household_power_consumption.txt',header=TRUE,sep=";",stringsAsFactors = FALSE)
#change the format of date and time
mydata<-subset(powerdata, Date %in% c('1/2/2007',"2/2/2007"))
mydata$Date<-as.Date(mydata$Date,"%d/%m/%Y")
newtime<-as.POSIXct(strptime(paste(mydata$Date, mydata$Time,sep = ' '),"%Y-%m-%d %H:%M:%S"))
mydata$weekdays<-weekdays(mydata$Date)
mydata$Global_active_power<-as.numeric(mydata$Global_active_power)
#plotting
attach(mydata)
png(filename = "plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
plot(newtime, mydata$Global_active_power,xlab='',ylab='Global active power',type = 'l',cex.lab=0.75,cex.axis=0.75)
plot(newtime, Voltage,xlab='datetime',ylab='Voltage',type = 'l',cex.lab=0.75,cex.axis=0.75)
plot(newtime,Sub_metering_1,xlab='',ylab='Energy sub metering',type="l",cex.lab=0.75,cex.axis=0.75)
lines(newtime,Sub_metering_2,col="red")
lines(newtime,Sub_metering_3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"),cex=0.35)
plot(newtime, Global_reactive_power,xlab='datetime',ylab='Global_reactive_power',type = 'l',cex.lab=0.75,cex.axis=0.75)
dev.off()
